### ISSUE TITLE
Deploy does not seem to "finish"

### ISSUE THREAD

**Issue by DeanmvSG** [mdyd-dev/marketplace-kit#106]
## Expected behavior 
After a deploy has finished, the command to "close" and the return to my normal default state of folder path

## Actual behavior
Deploy finishes (correctly!) and I have to `ctrl+c` to "end" it
<img width="611" alt="screenshot 2018-12-17 at 16 57 40" src="https://user-images.githubusercontent.com/15265711/50102501-2041c880-021d-11e9-9fa4-4335e6e0b85a.png">

## Steps to reproduce the problem
1. deploy a site

### Marketplace Kit
2.6.4

### NodeJs
11.4.0

### Operating System
macOS 10.14.2 (18C54)

## Notes:
I also use Hyper (https://hyper.is/) as my default terminal, it could be an issue with that, then again I've not seen this happen in previous versions of mpkit.

**Comment by pavelloz** [comment]
IMO Suspected commit - https://github.com/mdyd-dev/marketplace-kit/commit/9371c410942e3e8aa27d124635dd4e776fd9b17c

@DeanmvSG since you are the only one having the issue (and probably the only one using this terminal as well ;) ) and you are advanced enough:

Can you revert this commit locally (assuming you have mpkit installed with `npm link` - as far as i remember you got it once at least) and see if that helps?

**Comment by DeanmvSG** [comment]
I removed the line from mpkit in `/usr/local/bin/...` and rebooted terminal but it did the same thing. Not sure if that was enough to make this work or not? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mattwalter91** [comment]
This happens to me too. I'm Windows using VSCode's terminal. I have to manually close all deploys, whether they success or fail. Running v2.6.6 now.

**Comment by DeanmvSG** [comment]
Weirdly, this seems fine for me now! 👍

**Comment by pavelloz** [comment]
@DeanmvSG 
Did you change node version by any chance?

**Comment by DeanmvSG** [comment]
@pavelloz most likely I did, I ran a `brew update/upgrade` so it would have upgraded my node version as it comes through brew
